# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  ef:
    build:
      context: "/Users/dstakhurskyi/RiderProjects/PowerOutageManagement"
      dockerfile: "backend/PowerOutageService/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/PowerOutageService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "poweroutageservice:dev"
    ports: []
    volumes:
    - "/Users/dstakhurskyi/.nuget/packages:/root/.nuget/packages"
    - "/Users/dstakhurskyi/RiderProjects/PowerOutageManagement/backend/PowerOutageService:/app:rw"
    - "/Users/dstakhurskyi/RiderProjects/PowerOutageManagement/backend:/src:rw"
    working_dir: "/app"
  power-outage-api:
    build:
      context: "/Users/dstakhurskyi/RiderProjects/PowerOutageManagement"
      dockerfile: "backend/PowerOutageService/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/PowerOutageService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "poweroutageservice:dev"
    ports: []
    volumes:
    - "/Users/dstakhurskyi/.nuget/packages:/root/.nuget/packages"
    - "/Users/dstakhurskyi/RiderProjects/PowerOutageManagement/backend/PowerOutageService:/app:rw"
    - "/Users/dstakhurskyi/RiderProjects/PowerOutageManagement/backend:/src:rw"
    working_dir: "/app"
